name: gp_2025_11
description: A new Flutter project.
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0
  cloud_functions: ^5.1.4
  image_picker: ^1.1.2
  provider: ^6.1.2
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.2
  http: ^1.2.2
  file_picker: ^10.3.3
  iconsax_flutter: ^1.0.1
  dotted_border: ^3.1.0
  awesome_dialog: ^3.3.0
  dropdown_button2: ^2.3.9
  share_plus: ^10.1.2
  syncfusion_flutter_pdfviewer: ^28.1.33
  path_provider: ^2.1.5  
  device_info_plus: ^11.5.0
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.21
  camera: ^0.11.3
  permission_handler: ^12.0.1
  record: ^6.2.0
  flutter_tts: ^4.2.5
  just_audio: ^0.10.5
  google_mlkit_face_detection: ^0.10.0
  firebase_messaging: ^15.2.10
  dio: ^5.9.2
  open_filex: ^4.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: false
  adaptive_icon_background: "#3d3c85"
  image_path: "assets/images/JadeerAppLogo.png"
  remove_alpha_ios: false